/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import classes.Disciplina;
import javax.swing.JOptionPane;

/**
 *
 * @author carol
 */
public class TelaCadastro extends javax.swing.JDialog {

    private int index = -1;

    //se for -1 é uma inclusao e se for diferente é uma alteração!!
    public void setIndex(int index) {
        this.index = index;
        if (index >= 0) {
            Disciplina d = Main.listaD.get(index);
            txtNome.setText(d.getNome());
            txtProfessor.setText(d.getProfessor());
            txtHoras.setText(Integer.toString(d.getHoras()));
            switch (d.getSemestre()) {
                case 1 -> rbPrimeiro.setSelected(true);
                case 2 -> rbSegundo.setSelected(true);
                case 3 -> rbTerceiro.setSelected(true);
                case 4 -> rbQuarto.setSelected(true);
                case 5 -> rbQuinto.setSelected(true);
                case 6 -> rbSexto.setSelected(true);
                default -> rbPrimeiro.setSelected(true);
            }
        }
    }

    public TelaCadastro() {
        initComponents();
    }

    private void limparCampos() {
        //limpa todos os campos da tela
        txtNome.setText("");
        txtProfessor.setText("");
        txtHoras.setText("");
        buttonGroup1.clearSelection();
        txtNome.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        rbPrimeiro = new javax.swing.JRadioButton();
        rbSegundo = new javax.swing.JRadioButton();
        rbTerceiro = new javax.swing.JRadioButton();
        rbQuarto = new javax.swing.JRadioButton();
        rbQuinto = new javax.swing.JRadioButton();
        rbSexto = new javax.swing.JRadioButton();
        btnSalvar = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        txtHoras = new javax.swing.JTextField();
        txtProfessor = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tela de Cadastro");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Nome:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Professor:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Horas:");

        buttonGroup1.add(rbPrimeiro);
        rbPrimeiro.setText("1º Semestre");

        buttonGroup1.add(rbSegundo);
        rbSegundo.setText(" 2º Semestre");

        buttonGroup1.add(rbTerceiro);
        rbTerceiro.setText(" 3º Semestre");

        buttonGroup1.add(rbQuarto);
        rbQuarto.setText(" 4º Semestre");

        buttonGroup1.add(rbQuinto);
        rbQuinto.setText(" 5º Semestre");

        buttonGroup1.add(rbSexto);
        rbSexto.setText(" 6º Semestre");

        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/disquete.png"))); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/fechar (2).png"))); // NOI18N
        btnSair.setText("Sair");
        btnSair.setPreferredSize(new java.awt.Dimension(70, 20));
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        txtHoras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHorasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addContainerGap(251, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtNome, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
                            .addComponent(txtProfessor, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtHoras, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSair, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSalvar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbSegundo)
                    .addComponent(rbPrimeiro)
                    .addComponent(rbTerceiro))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(rbQuinto)
                    .addComponent(rbQuarto)
                    .addComponent(rbSexto))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtHoras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbPrimeiro)
                    .addComponent(rbQuarto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbSegundo)
                    .addComponent(rbQuinto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbTerceiro)
                    .addComponent(rbSexto, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        //tentar converter horas para inteiro
        int horas = 0;
        try {
            horas = Integer.valueOf(txtHoras.getText());
        } catch (Exception e) {
            e.printStackTrace();
        }

        //convertendo em semestres
        int semestre = 0;
        if (rbPrimeiro.isSelected()) {
            semestre = 1;
        } else if (rbSegundo.isSelected()) {
            semestre = 2;
        } else if (rbTerceiro.isSelected()) {
            semestre = 3;
        } else if (rbQuarto.isSelected()) {
            semestre = 4;
        } else if (rbQuinto.isSelected()) {
            semestre = 5;
        } else if (rbSexto.isSelected()) {
            semestre = 6;
        }

        if (txtNome.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Preencha o campo nome!");
            txtNome.requestFocus();
        } else if (txtProfessor.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Preencha o campo professor!");
            txtProfessor.requestFocus();
        } else if (horas <= 0) {
            JOptionPane.showMessageDialog(rootPane, "Horas precisa ser maior que zero(0)!");
            txtHoras.requestFocus();
        } else if (semestre == 0) {
            JOptionPane.showMessageDialog(rootPane, "Selecione um semestre nas opções!");
            rbPrimeiro.requestFocus();
        } else {
            //não preciso mais testar, todos os campos foram validados
            //criar a disciplina e adicionar na lista
            Disciplina d = new Disciplina(txtNome.getText(), txtProfessor.getText(), horas, semestre);
            //disciplina criado
            System.out.println("Disciplina criada" + d);
            //adicionando na lista
            JOptionPane.showMessageDialog(this, "Disciplina Criada");
            //adicionar ou editar verificação
            if (index == -1) {
                Main.listaD.add(d);
                rbPrimeiro.setSelected(true);
                limparCampos();
            }else{
                Main.listaD.alterar(d, index);
                dispose();
            }
            
            System.out.println("-------------------------------");
            System.out.println(Main.listaD);
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void txtHorasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHorasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHorasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnSalvar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JRadioButton rbPrimeiro;
    private javax.swing.JRadioButton rbQuarto;
    private javax.swing.JRadioButton rbQuinto;
    private javax.swing.JRadioButton rbSegundo;
    private javax.swing.JRadioButton rbSexto;
    private javax.swing.JRadioButton rbTerceiro;
    private javax.swing.JTextField txtHoras;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtProfessor;
    // End of variables declaration//GEN-END:variables
}
