/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import classes.Disciplina;
import javax.swing.JOptionPane;

/**
 *
 * @author carol
 */
public class TelaRelatorio extends javax.swing.JFrame {

    /**
     * Creates new form TelaRelatorio
     */
    public TelaRelatorio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ckListarTodas = new javax.swing.JCheckBox();
        ckQuantidade = new javax.swing.JCheckBox();
        ckTotal = new javax.swing.JCheckBox();
        btnRelatorio = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Relatório");
        setResizable(false);

        ckListarTodas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ckListarTodas.setText("Listar todas as disciplinas cadastradas");

        ckQuantidade.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ckQuantidade.setText("Quantidade de disciplinas por semestre");

        ckTotal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ckTotal.setText("Total de horas das disciplinas");
        ckTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckTotalActionPerformed(evt);
            }
        });

        btnRelatorio.setText("Relatório");
        btnRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRelatorioActionPerformed(evt);
            }
        });

        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ckTotal)
                    .addComponent(ckQuantidade)
                    .addComponent(btnRelatorio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSair, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ckListarTodas))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(ckListarTodas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ckQuantidade)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ckTotal)
                .addGap(18, 18, 18)
                .addComponent(btnRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSair)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ckTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ckTotalActionPerformed

    private void btnRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRelatorioActionPerformed
        String relatorio = "";

        if (ckListarTodas.isSelected()) {
            relatorio = Main.listaD.toString();
            relatorio += "\n==============================\n";
        }

        int[] arraySemestre = new int[6];
        int totalHoras = 0;

        //for para percorrer a minha lista de disciplinas criadas
        for (int i = 0; i < Main.listaD.size(); i++) {
            //armazena a disciplina que esta sendo percorrida pelo for
            Disciplina d = Main.listaD.get(i);
            //armazena as horas da disciplina que esta sendo percorrida pelo for
            totalHoras += d.getHoras();
            //armazena o semestre da disciplina que esta sendo percorrida pelo for
            //0 a 5 --- semestres 1 - 6// semestre 1 = 0, semestre 2 = 1///
            //se o semestre da disciplina for 6 ele vai cair no indice 5//
            arraySemestre[d.getSemestre() - 1]++;
        }

        if (ckQuantidade.isSelected()) {
            for (int i = 0; i < arraySemestre.length; i++) {
                relatorio += "Semestre " + (i + 1) + ": " + arraySemestre[i] + "\n";
            }
            relatorio += "\n==============================\n";
        }

        if (ckTotal.isSelected()) {
            relatorio += "Total de horas: " + totalHoras;
            relatorio += "\n==============================\n";
        }

        if (relatorio.equals("")) {
            JOptionPane.showMessageDialog(this, "Escolha pelo menos uma das opções!");
        } else {
            JOptionPane.showMessageDialog(this, relatorio);
        }
    }//GEN-LAST:event_btnRelatorioActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        dispose();
    }//GEN-LAST:event_btnSairActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRelatorio;
    private javax.swing.JButton btnSair;
    private javax.swing.JCheckBox ckListarTodas;
    private javax.swing.JCheckBox ckQuantidade;
    private javax.swing.JCheckBox ckTotal;
    // End of variables declaration//GEN-END:variables
}
